name: build armv8 openwrt

on:
  #è‡ªåŠ¨ç¼–è¯‘ï¼šæ¯ä¸ªæœˆ15/28æ—©ä¸Š4ç‚¹
  #  schedule:
  #    - cron: 0 16 15,28 * *
  workflow_call:
    inputs:
      source:
        description: 'é€‰æ‹©è¦ç¼–è¯‘çš„æºç ç‰ˆæœ¬ï¼Œå¯é€‰ï¼š18.06, 24.10'
        required: true
        default: '18.06'
        type: string
  workflow_dispatch:
    inputs:
      source:
        description: 'é€‰æ‹©è¦ç¼–è¯‘çš„LUCIç‰ˆæœ¬'
        required: true
        default: '18.06'
        type: choice
        options: ['18.06', '24.10']
      ip:
        description: 'è®¾ç½®é»˜è®¤ç™»å½•IP'
        required: false
        default: '192.168.2.254'
      toolchain:
        description: 'ä½¿ç”¨toolchainç¼“å­˜'
        required: false
        default: true
        type: boolean
      zsh_tool:
        description: 'é¢„è®¾zshç»ˆç«¯å·¥å…·'
        required: false
        default: true
        type: boolean
      openclash:
        description: 'é¢„è®¾openclashå†…æ ¸'
        required: false
        default: 'arm64'
        type: choice
        options: [amd64, arm64, armv7, armv6, armv5]
      openwrt_board:
        description: 'è®¾ç½®è®¾å¤‡(CPU)å‹å·'
        required: false
        default: 's905d_qemu'
      openwrt_kernel:
        description: "é€‰æ‹©æ¨¡ç³Šå†…æ ¸ç‰ˆæœ¬ï¼Œå’Œè¾“å…¥çš„æ˜¯2é€‰ä¸€ï¼Œå–æœ€æ–°"
        required: true
        default: "6.1.y_6.6.y_6.12.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 5.4.y_5.10.y_5.15.y
          - 5.15.y_6.1.y
          - 6.1.y_6.6.y_6.12.y
      input_kernel:
        description: 'è¾“å…¥å…·ä½“å†…æ ¸ç‰ˆæœ¬ï¼Œå’Œé€‰æ‹©çš„æ˜¯2é€‰ä¸€'
        required: false
        default: '6.6.116'
        type: string
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: true
        default: "laiyujun/kernel"
        type: choice
        options:
          - ophub/kernel
          - laiyujun/kernel
      kernel_usage:
        description: "Set the tags of the stable kernel."
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - flippy
      artifact:
        description: 'ä¸Šä¼ å›ºä»¶åˆ°Artifact'
        required: false
        default: false
        type: boolean
      release:
        description: 'ä¸Šä¼ å›ºä»¶åˆ°Releases'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build armv8 ${{ inputs.source || '18.06' }}

    env:
      DEFAULT_IP: ${{ inputs.ip || '192.168.2.254' }}
      TOOLCHAIN: ${{ inputs.toolchain || true }}
      ZSH_TOOL: ${{ inputs.zsh_tool || true }}
      CLASH_KERNEL: ${{ inputs.openclash || 'arm64' }}
      OPENWRT_BOARD: ${{ inputs.openwrt_board || 's905d_qemu' }}
      OPENWRT_KERNEL: ${{ inputs.openwrt_kernel || '6.6.y' }}
      AUTO_KERNEL: ${{ inputs.auto_kernel || true }}
      INPUT_KERNEL: ${{ inputs.input_kernel || '6.6.116' }}
      KERNEL_REPO: ${{ inputs.kernel_repo || 'laiyujun/kernel' }}
      KERNEL_USAGE: ${{ inputs.kernel_usage || 'stable' }}
      CONFIG_FILE: configs/armv8-${{ inputs.source || '18.06' }}.config
      APP_CONFIG_FILE: configs/app.config
      DIY_SCRIPT: diy-${{ inputs.source || '18.06' }}.sh
      RELEASE_TAG: armv8-${{ inputs.source || '18.06' }}
      TOOLCHAIN_TAG: toolchain
      UPLOAD_BIN_DIR: false
      UPLOAD_TO_ARTIFACT: ${{ inputs.artifact || false }}
      UPLOAD_TO_RELEASE: ${{ inputs.release || true }}
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Server Performance
        run: |
          echo "è­¦å‘Šâš "
          echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
          echo -e "å·²çŸ¥CPUå‹å·(é™åº): 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
          echo "==========================CPUä¿¡æ¯=========================="
          echo "CPUç‰©ç†æ•°é‡: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPUçº¿ç¨‹æ•°é‡: $(nproc)"
          echo -e "CPUå‹å·ä¿¡æ¯:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "==========================å†…å­˜ä¿¡æ¯=========================="
          echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "==========================ç¡¬ç›˜ä¿¡æ¯=========================="
          echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install dos2unix rename
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          sudo timedatectl set-timezone "$TZ"        
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}
          
          # æ£€æŸ¥ rename å‘½ä»¤æ˜¯å¦å­˜åœ¨
          if ! command -v rename &> /dev/null; then
            echo "rename command not found, using fallback method"
          else
            echo "rename command can be used."
          fi

      - name: Combine Disks
        run: |
          MNT_SIZE=$((($(df --block-size=1024 --output=avail /mnt | tail -1) - 1024*1024*1) * 1024))
          sudo fallocate -l $MNT_SIZE /mnt/mnt.img
          MNT_NAME=$(sudo losetup -Pf --show /mnt/mnt.img)
          sudo pvcreate -f $MNT_NAME
          ROOT_SIZE=$((($(df --block-size=1024 --output=avail / | tail -1) - 1024*1024*4) * 1024))
          sudo fallocate -l $ROOT_SIZE /root.img
          ROOT_NAME=$(sudo losetup -Pf --show /root.img)
          sudo pvcreate -f $ROOT_NAME
          sudo vgcreate actions $MNT_NAME $ROOT_NAME
          sudo lvcreate -n disk -l 100%FREE actions
          LV_NAME=$(sudo lvscan | awk -F "'" '{print $2}')
          sudo mkfs.btrfs -L combinedisk $LV_NAME
          sudo mkdir -p /workdir
          sudo mount -o compress=zstd $LV_NAME /workdir
          sudo chown -R runner:runner /workdir && df -hT

      - name: Load Compile Script
        run: chmod +x $DIY_SCRIPT && ./$DIY_SCRIPT

      - name: Compile Toolchain
        if: env.REBUILD_TOOLCHAIN == 'true'
        id: toolchain
        run: |
          cd $OPENWRT_PATH
          make toolchain/compile -j$(nproc) || make toolchain/compile -j1 V=s
          $GITHUB_WORKSPACE/$DIY_SCRIPT

      - name: Delete Old Toolchain
        if: steps.toolchain.conclusion == 'success' || env.OUTPUT_RELEASE == 'true'
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TOOLCHAIN_TAG }}
          assets: '${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}*'
          fail-if-no-assets: false
          fail-if-no-release: false

      - name: Upload Toolchain To Release
        if: steps.toolchain.conclusion == 'success' || env.OUTPUT_RELEASE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: toolchain-cache
          tag_name: ${{ env.TOOLCHAIN_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*
          body: OpenWrt å·¥å…·é“¾ç¼“å­˜

      - name: Download DL Package
        run: |
          cd $OPENWRT_PATH
          # make download -j$(nproc)
          make package/download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile Firmware
        id: compile
        run: |
          cd $OPENWRT_PATH
          mkdir -p files/etc/uci-defaults
          cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s
          echo "FILE_DATE=$(date +"%Y.%m.%d")" >>$GITHUB_ENV
          echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >>$GITHUB_ENV

      - name: Upload Bin Directory
        if: steps.compile.conclusion == 'success' && env.UPLOAD_BIN_DIR == 'true'
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-bin-${{ env.FILE_DATE }}
          path: ${{ env.OPENWRT_PATH }}/bin

      - name: Packaging OpenWrt For Auto Kernel
        if: steps.compile.conclusion == 'success' && env.AUTO_KERNEL == 'true'
        uses: haiibo/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMSR: openwrt/bin/targets/*/*/*rootfs.tar.gz
          PACKAGE_SOC: ${{ env.OPENWRT_BOARD }}
          KERNEL_REPO_URL: ${{ env.KERNEL_REPO }}
          KERNEL_VERSION_NAME: ${{ env.OPENWRT_KERNEL }}
          KERNEL_AUTO_LATEST: ${{ env.AUTO_KERNEL }}

      - name: Packaging OpenWrt For Input Kernel
        if: steps.compile.conclusion == 'success' && env.AUTO_KERNEL == 'false'
        uses: haiibo/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMSR: openwrt/bin/targets/*/*/*rootfs.tar.gz
          PACKAGE_SOC: ${{ env.OPENWRT_BOARD }}
          KERNEL_REPO_URL: ${{ env.KERNEL_REPO }}
          KERNEL_VERSION_NAME: ${{ env.INPUT_KERNEL }}
          KERNEL_AUTO_LATEST: ${{ env.AUTO_KERNEL }}

      - name: Organize Files
        if: env.PACKAGED_STATUS == 'success'
        run: |
          df -hT
          echo "==============================="
          ls $OPENWRT_PATH/bin/targets/*/*
          echo "==============================="
          cd $OPENWRT_PATH/bin/targets/*/*
          cat config.buildinfo
          cp -rf $OPENWRT_PATH/bin/packages/* packages
          tar -zcf packages.tar.gz packages
          sleep 3s && rm -rf packages u-boot-qemu* sha256sums *.buildinfo *.manifest *.bin
          sed '/^$/d' $OPENWRT_PATH/.config >config.txt
          echo "FIRMWARE_PATH=$PWD" >>$GITHUB_ENV
          cd $PACKAGED_OUTPUTPATH && rm -f *rootfs.tar.gz *.sha
          if [[ $SOURCE_REPO == 'immortalwrt' ]]; then
            rename 's/openwrt/${{ env.SOURCE_REPO }}/' *
          fi

      - name: Upload OpenWrt To Artifact
        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_TO_ARTIFACT == 'true'
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-firmware-${{ env.FILE_DATE }}
          path: ${{ env.PACKAGED_OUTPUTPATH }}
          overwrite: true

      - name: Upload OpenWrt To Release
        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_TO_RELEASE == 'true'
        uses: ncipollo/release-action@main
        with:
          name: ${{ env.DATE }} for ${{ env.DEVICE_TARGET }}
          allowUpdates: true
          removeArtifacts: true
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.FIRMWARE_PATH }}/*,${{ env.PACKAGED_OUTPUTPATH }}/*
          body: |
            **This is ${{ env.SOURCE_REPO }} firmware for ${{ env.DEVICE_TARGET }}**
            ### ğŸ“’ å›ºä»¶ä¿¡æ¯
            - ğŸ’» å¹³å°æ¶æ„: ${{ env.DEVICE_TARGET }}
            - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
            - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
            - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL_VERSION }}
            - ğŸŒ é»˜è®¤åœ°å€: ${{ env.DEFAULT_IP }}
            - ğŸ”‘ é»˜è®¤å¯†ç : password
            ### ğŸ§Š å›ºä»¶ç‰ˆæœ¬
            - å›ºä»¶ç¼–è¯‘å‰æœ€åä¸€æ¬¡â¦[ä¸»æºç ](${{ env.REPO_URL }})æ›´æ–°è®°å½•
            - ${{ env.COMMIT_AUTHOR }}
            - ${{ env.COMMIT_DATE }}
            - ${{ env.COMMIT_MESSAGE }}
            - ${{ env.COMMIT_HASH }}
