name: delete old workflows

on:
#  schedule: [cron: 0 17 * * 5]
  workflow_call:
    inputs:
      releases_keep_latest:
        description: '保留最新Releases数量'
        required: false
        type: number
        default: 5
      workflows_keep_day:
        description: '保留最新workflows天数'
        required: false
        type: number
        default: 30
  workflow_dispatch:
    inputs:
      releases_keep_latest:
        description: '保留最新Releases数量'
        required: false
        default: 5
        type: choice
        options: [ 30, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 ]
      workflows_keep_day:
        description: '保留Workflows天数'
        required: false
        default: 30
        type: choice
        options: [ 30, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 ]

env:
  TZ: Asia/Shanghai

jobs:
  cleaning:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo timedatectl set-timezone "$TZ"

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: ${{ github.event.inputs.releases_keep_latest }}
          releases_keep_keyword: 'toolchain'
          delete_workflows: true
          workflows_keep_day: ${{ github.event.inputs.workflows_keep_day }}
          out_log: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}
